In [42]:
import pickle
import numpy as np
import torch
file_path = '/Users/mtcd/@codes/DC3-main-adapted/datasets/nonlinear/random_nonlinear_dataset_ex30'

with open(file_path, 'rb') as f:
    data = pickle.load(f)   
    
    

In [43]:
data.trainX


tensor([[1.1787, 2.1223],
        [0.7661, 0.2716],
        [3.1479, 2.6253],
        [2.5501, 2.3024],
        [0.1563, 1.4313],
        [3.7827, 0.2402],
        [3.4562, 3.5092],
        [0.2048, 2.6097],
        [2.2070, 2.3901],
        [1.9341, 1.1320],
        [1.1909, 2.2460],
        [1.5842, 3.1548],
        [1.6739, 0.5756],
        [0.6036, 0.2210],
        [2.8721, 1.1693],
        [0.7951, 3.3255],
        [2.2720, 0.3294],
        [2.1800, 0.6358],
        [2.7070, 0.4739],
        [1.7800, 3.5519],
        [3.1891, 0.2719],
        [3.8432, 2.6368],
        [2.8751, 2.9743],
        [3.5509, 0.5358],
        [3.1079, 3.3520]])

In [44]:
data.obj_fn(data.trainX)

tensor([ 5.0816,  4.2420,  9.4734,  6.5592,  4.9659, 59.2157, 10.0425,  5.8167,
         5.5308,  6.1171,  5.3623,  8.2492,  6.4735,  4.2455, 15.8336,  9.1328,
        14.1916, 10.5904, 20.4141, 10.1972, 35.9304, 17.6762,  7.5443, 42.7897,
         8.6284])

In [45]:
data.ineq_dist(data.trainX,0)

tensor([[ 1.6680],
        [ 0.0000],
        [ 8.6552],
        [ 5.7025],
        [ 0.0304],
        [10.2462],
        [11.5374],
        [ 1.2340],
        [ 4.5812],
        [ 2.6259],
        [ 1.8249],
        [ 3.8704],
        [ 1.6844],
        [ 0.0000],
        [ 6.0287],
        [ 2.7388],
        [ 3.3985],
        [ 3.1654],
        [ 5.0522],
        [ 5.0303],
        [ 7.1461],
        [12.3156],
        [ 7.9113],
        [ 9.0287],
        [ 9.5532]])

In [49]:
results_non_compl = [[ 4.7959e-01,  7.7648e-01],
        [ 5.1282e-01,  5.0120e-01],
        [-2.6602e+01,  2.3353e+01],
        [-3.0634e+01,  2.8261e+01],
        [ 2.0380e-01,  3.1124e-01],
        [ 1.6028e-01,  1.8688e-01],
        [-5.3553e-02,  1.4685e-01],
        [-1.2492e+01,  1.1212e+01],
        [-1.1247e+02,  9.6038e+01],
        [ 7.5974e-02,  2.5417e-01],
        [-1.8367e+00,  3.7427e+00],
        [-4.2329e+00,  5.4248e+00],
        [ 1.2940e+00, -4.2653e-01],
        [-5.3638e+00,  4.8913e+00],
        [ 1.5253e+00,  1.3596e+00],
        [-3.2504e+01,  2.9006e+01],
        [-6.6472e+01,  5.8607e+01],
        [ 1.3215e+00,  1.5125e-01],
        [ 1.3777e-01,  2.8755e-01],
        [-1.3302e+02,  1.1833e+02],
        [-2.2598e+00,  3.2739e+00],
        [ 9.8829e-01,  2.1544e-01],
        [-3.3180e-01,  4.0966e-01],
        [ 1.7294e+00,  1.8248e-01],
        [ 8.7343e-01, -5.2234e-03]]


results_with_compl = [[-0.3679,  0.8688],
        [-0.3601,  0.8699],
        [-1.1348,  0.6089],
        [-1.6424,  0.0000],
        [ 0.3459,  0.8719],
        [ 0.3177,  0.8754],
        [-0.2248,  0.8850],
        [ 1.2360,  0.5392],
        [-0.9771,  0.6941],
        [-0.7260,  0.7901],
        [-0.7921,  0.7687],
        [-1.0932,  0.6337],
        [-0.1628,  0.8895],
        [-0.5679,  0.8322],
        [ 0.6896,  0.8009],
        [-0.4986,  0.8468],
        [-1.8308,  0.0000],
        [-0.1451,  0.8905],
        [-0.2754,  0.8802],
        [-0.6375,  0.8152],
        [ 0.5611,  0.8337],
        [ 0.1633,  0.8894],
        [-0.7482,  0.7832],
        [-0.8852,  0.7340],
        [-2.3565,  0.0000]]

In [50]:

for i in results_with_compl:
    #print('Resultado: ', data.obj_fn(i))
    j = torch.tensor([i])
    print(i)
    print('Resultado: ', data.obj_fn(j))
    print('--')
    



[-0.3679, 0.8688]
Resultado:  tensor([5.3085])
--
[-0.3601, 0.8699]
Resultado:  tensor([5.3051])
--
[-1.1348, 0.6089]
Resultado:  tensor([5.1070])
--
[-1.6424, 0.0]
Resultado:  tensor([6.5519])
--
[0.3459, 0.8719]
Resultado:  tensor([4.5235])
--
[0.3177, 0.8754]
Resultado:  tensor([4.5643])
--
[-0.2248, 0.885]
Resultado:  tensor([5.2233])
--
[1.236, 0.5392]
Resultado:  tensor([4.6558])
--
[-0.9771, 0.6941]
Resultado:  tensor([5.1800])
--
[-0.726, 0.7901]
Resultado:  tensor([5.3103])
--
[-0.7921, 0.7687]
Resultado:  tensor([5.2820])
--
[-1.0932, 0.6337]
Resultado:  tensor([5.1214])
--
[-0.1628, 0.8895]
Resultado:  tensor([5.1718])
--
[-0.5679, 0.8322]
Resultado:  tensor([5.3451])
--
[0.6896, 0.8009]
Resultado:  tensor([4.1049])
--
[-0.4986, 0.8468]
Resultado:  tensor([5.3433])
--
[-1.8308, 0.0]
Resultado:  tensor([5.8769])
--
[-0.1451, 0.8905]
Resultado:  tensor([5.1556])
--
[-0.2754, 0.8802]
Resultado:  tensor([5.2589])
--
[-0.6375, 0.8152]
Resultado:  tensor([5.3361])
--
[0.5611, 0.83

In [8]:
import pickle
import numpy as np
import torch
file_path = '/Users/mtcd/@codes/DC3-main-adapted/datasets/nonlinear/random_nonlinear_dataset_ex30'

with open(file_path, 'rb') as f:
    data = pickle.load(f)   
    
    

In [10]:
data.trainX

tensor([[1.1787, 2.1223],
        [0.7661, 0.2716],
        [3.1479, 2.6253],
        [2.5501, 2.3024],
        [0.1563, 1.4313],
        [3.7827, 0.2402],
        [3.4562, 3.5092],
        [0.2048, 2.6097],
        [2.2070, 2.3901],
        [1.9341, 1.1320],
        [1.1909, 2.2460],
        [1.5842, 3.1548],
        [1.6739, 0.5756],
        [0.6036, 0.2210],
        [2.8721, 1.1693],
        [0.7951, 3.3255],
        [2.2720, 0.3294],
        [2.1800, 0.6358],
        [2.7070, 0.4739],
        [1.7800, 3.5519],
        [3.1891, 0.2719],
        [3.8432, 2.6368],
        [2.8751, 2.9743],
        [3.5509, 0.5358],
        [3.1079, 3.3520]])

In [4]:
import numpy as np
from scipy.optimize import minimize

# Definindo a função objetivo
def obj_fn(x):
    x1 = x[0]
    x2 = x[1]
    return x1 * ((x1 - x2) ** 2 + (x1 - 2)) + 5

# Restrição de igualdade
def eq_resid(x):
    x1 = x[0]
    x2 = x[1]
    return 0.5 * x1**2 + 1.5 * x2**2 - 1.2

# Restrição de desigualdade
def ineq_resid(x):
    x1 = x[0]
    x2 = x[1]
    return 0.75 * x1**2 + 0.25 * x2**2 - 0.5

# Definindo as restrições no formato esperado pelo `minimize`
constraints = [
    # Restrição de igualdade (deve ser igual a 0)
    {'type': 'eq', 'fun': eq_resid},
    
    # Restrição de desigualdade (deve ser menor ou igual a 0)
    {'type': 'ineq', 'fun': ineq_resid}
]

# Palpite inicial para as variáveis de decisão (x1, x2)
x0 = np.array([2.4, 0.3])

# Resolvendo o problema de otimização
result = minimize(obj_fn, x0, constraints=constraints, method='SLSQP')

# Verificando o resultado
if result.success:
    print(f"Valor ótimo encontrado: {result.x}")
    print(f"Valor da função objetivo no ótimo: {result.fun}")
else:
    print("A otimização não convergiu:", result.message)


Valor ótimo encontrado: [0.85835339 0.74458702]
Valor da função objetivo no ótimo: 4.0311732480156275
